abbr -a -- dcl 'docker container ls'
abbr -a -- de 'docker exec -it'
abbr -a -- di 'docker inspect'
abbr -a -- dil 'docker image ls'
abbr -a -- dl 'docker logs'
abbr -a -- dp 'docker ps'
abbr -a -- dpa 'docker ps --all'
abbr -a -- dr 'doppler run --'
abbr -a -- drdc 'doppler run -- docker compose'
abbr -a -- drpi 'doppler run -- pdm install'
abbr -a -- drpr 'doppler run -- pdm run'
abbr -a -- drprp 'doppler run -- pdm run python'
abbr -a -- drprv 'doppler run -- pdm run lvim'
abbr -a -- drps 'doppler run -- pdm sync'
abbr -a -- drpu 'doppler run -- pdm update'
abbr -a -- dry 'doppler run -- yarn'
abbr -a -- dryb 'doppler run -- yarn build'
abbr -a -- ds 'doppler setup'
abbr -a -- dsl 'docker service ls'
abbr -a -- dss 'doppler secrets'
abbr -a -- dtl 'docker stack ls'
abbr -a -- dtp 'docker stack ps'
