abbr -a -- g git
abbr -a -- ga 'git add'
abbr -a -- gb 'git branch'
abbr -a -- gba 'git branch -a'
abbr -a -- gc 'git commit -v'
abbr -a -- gc! 'git commit -v --amend'
abbr -a -- gca 'git commit -v -a'
abbr -a -- gca! 'git commit -v -a --amend'
abbr -a -- gch 'git checkout'
abbr -a -- gchm 'git checkout master'
abbr -a -- gchw 'git checkout working'
abbr -a -- gcl 'git config --list'
abbr -a -- gclean 'git reset --hard; and git clean -dfx'
abbr -a -- gcm 'git commit -m'
abbr -a -- gcm! 'git commit --amend -m'
abbr -a -- gcount 'git shortlog -sn'
abbr -a -- gcp 'git cherry-pick'
abbr -a -- gd 'git diff'
abbr -a -- gdc 'git diff --cached'
abbr -a -- gds 'git diff --staged'
abbr -a -- gl 'git pull'
abbr -a -- glg 'git log --stat --max-count=10'
abbr -a -- glgg 'git log --graph --max-count=10'
abbr -a -- glgga 'git log --graph --decorate --all'
abbr -a -- glo 'git log --oneline'
abbr -a -- gls 'git ls-files'
abbr -a -- glsf 'git ls-files | grep'
abbr -a -- gm 'git merge'
abbr -a -- gp 'git push'
abbr -a -- gr 'git reset'
abbr -a -- grh 'git reset HEAD'
abbr -a -- grha 'git reset --hard'
abbr -a -- grhh 'git reset HEAD --hard'
abbr -a -- grm 'git remote'
abbr -a -- grmv 'git remote -v'
abbr -a -- grt 'cd (git rev-parse --show-toplevel; or echo ".")'
abbr -a -- grup 'git remote update'
abbr -a -- gs 'git status'
abbr -a -- gss 'git status -s'
abbr -a -- gst 'git stash'
abbr -a -- gstd 'git stash drop'
abbr -a -- gstp 'git stash pop'
abbr -a -- gsts 'git stash show --text'
abbr -a -- gsw 'git switch'
abbr -a -- gunwip 'git log -n 1 | grep -q -c wip; and git reset HEAD~1'
abbr -a -- gwc 'git whatchanged -p --abbrev-commit --pretty=medium'
abbr -a -- gwip 'git add -A; git ls-files --deleted -z | xargs -0 git rm; git commit -m "wip"'
