[theme]
theme = "plain"

[icons]
icons = "awesome6"

[[block]]
block = "disk_space"
format = " DISK: $free/$total ($percentage left)"


[[block]]
block = "sound"
format = " VOL: {$volume|N/A} "

[[block]]
block = "backlight"
format = " DIS $brightness "

[[block]]
block = "cpu"
interval = 5
format = " CPU: $utilization $frequency "

[[block]]
block = "load"
interval = 5
format = " LOAD: 1m avg $1m "

[[block]]
block = "temperature"
format = " TEMP: $average avg, $max max"

[[block]]
block = "memory"
interval = 5
format = " RAM: $mem_used/$mem_total $mem_used_percents "


[[block]]
block = "battery"
interval = 30
format = " BAT: $percentage $power "
full_format = "100%"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %m/%d %R') "
